# copy this file to .ci/deploy/testenv/edgar/docker-compose.override.yml to enable mTLS for EDGAR and CLEO services

x-edgar-mtls-params: &edgar-mtls-params
  environment:
    # EDGAR
    - OPENDUT_EDGAR_NETWORK_TLS_CLIENT_AUTH_ENABLED=true  # enable mTLS
    - OPENDUT_EDGAR_NETWORK_TLS_CLIENT_AUTH_CERTIFICATE=/provision/pki/deploy-intermediate/client-intermediate-test.pem
    - OPENDUT_EDGAR_NETWORK_TLS_CLIENT_AUTH_KEY=/provision/pki/deploy-intermediate/client-intermediate-test.key
    # Modify the location (JSON pointer) of the client certificate path in the NetBird client config (config.json)
    - OPENDUT_EDGAR_VPN_NETBIRD_CLIENT_CONFIG_KEYS_MTLS_CERTIFICATE=MgmtClientCert/CertPath
    - OPENDUT_EDGAR_VPN_NETBIRD_CLIENT_CONFIG_KEYS_MTLS_KEY=MgmtClientCert/KeyPath
    # CLEO
    - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_ENABLED=true  # enable mTLS
    - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_CERTIFICATE=/provision/pki/deploy-intermediate/client-intermediate-test.pem
    - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_KEY=/provision/pki/deploy-intermediate/client-intermediate-test.key

# test with curl
# docker exec -it edgar-leader curl -v --cert /provision/pki/deploy-intermediate/client-intermediate-test.pem --key /provision/pki/deploy-intermediate/client-intermediate-test.key -v https://opentelemetry.opendut.local

services:

  leader:
    <<: *edgar-mtls-params
  peer:
    <<: *edgar-mtls-params
