apiVersion: 1
datasources:
  - name: Loki
    uid: loki
    type: loki
    isDefault: true
    version: 1
    editable: false
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "TraceId=(\\w+)"
          name: TraceId
          url: "$${__value.raw}"
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"
  - name: Tempo
    uid: tempo
    type: tempo
    isDefault: false
    version: 1
    editable: false
    access: proxy
    url: http://tempo:3200
