# Configuration overrides during development
# Paths are relative to repository root

[network.tls]
certificate = "resources/development/tls/insecure-development-carl.pem"
key = "resources/development/tls/insecure-development-carl.key"
ca = "resources/development/tls/insecure-development-ca.pem"

[network.oidc]
enabled = false

[serve]
ui.directory = "./opendut-lea/dist/"

[vpn]
enabled = false

[opentelemetry]
endpoint = "http://localhost:4317"
