ARG OPENDUT_GRAFANA_TEMPO_VERSION

FROM grafana/tempo:$OPENDUT_GRAFANA_TEMPO_VERSION

# wget has been removed from the base image,
# see https://github.com/grafana/tempo/issues/5558
# and https://github.com/grafana/tempo/issues/5352#issuecomment-3552680224

COPY --from=busybox /lib/* /lib/
COPY --from=busybox /lib64/* /lib64/
COPY --from=busybox /bin/wget /bin/

# see https://github.com/grafana/tempo/blob/e957303cc96978d841f7facba75b54c2dd94af7c/cmd/tempo/Dockerfile
