# Docker container to provision the netbird management API

# Check the logs of the container or the following files for the API key and testenv setup key:
# docker exec -ti netbird-management_init-1 cat /management/api_key
# docker exec -ti netbird-management_init-1 cat /management/testenv_setup_key

FROM ubuntu:22.04
ARG PUID=1000
ARG PGID=1000
ARG PUSER
ARG PGROUP

RUN apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata ca-certificates curl jq && rm -rf /var/lib/apt/lists/*

# add the insecure development CA to the trust store
COPY ./resources/development/tls/ /opendut-tls/
COPY ./.ci/docker/netbird/add-root-certificates.sh /opendut-tls/add-root-certificates.sh
RUN chmod +x /opendut-tls/add-root-certificates.sh && /opendut-tls/add-root-certificates.sh

COPY ./.ci/docker/netbird/netbird-api-functions.sh /netbird-api-functions.sh
COPY ./.ci/docker/netbird/netbird-api-init.sh /netbird-api-init.sh

# create group and user as specified in build args (same as host of developer)
RUN groupadd -g ${PGID} ${PGROUP}
RUN useradd --no-log-init -m -u ${PUID} -g ${PGID} -o -s /bin/bash ${PUSER}

RUN mkdir /management
RUN chown ${PUSER}:${PGROUP} /management

ENTRYPOINT [ "/netbird-api-init.sh" ]
