---
version: "2.1"
services:
  firefox:
    build:
      context: ../../..
      dockerfile: ./.ci/docker/firefox/Dockerfile
    #image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=OpenDuT-Browser
      # dynamically provided
      - OPENDUT_CUSTOM_CA1
      - OPENDUT_CUSTOM_CA2
      - OPENDUT_HOSTS

    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    #restart: unless-stopped
    networks:
      - opendutnet

networks:
  opendutnet:
    name: opendut_network
    external: true  # Use a pre-existing network
