syntax = "proto3";

package opendut.carl.services.secret_manager;

import "opendut/model/secret/secret.proto";

service SecretManager {
  rpc StoreSecret(StoreSecretRequest) returns (StoreSecretResponse) {}
  rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse) {}
  rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse) {}
}

//
// StoreSecret
//
message StoreSecretRequest {
  opendut.model.secret.SecretDescriptor secret_descriptor = 1;
}

message StoreSecretResponse {
  oneof reply {
    StoreSecretSuccess success = 1;
    StoreSecretFailure failure = 2;
  }
}

message StoreSecretSuccess {
  opendut.model.secret.SecretId secret_id = 1;
}

message StoreSecretFailure {
  oneof error {
    StoreSecretFailureInternal internal = 1;
  }
}

message StoreSecretFailureInternal {
  opendut.model.secret.SecretId secret_id = 1;
  optional opendut.model.secret.SecretName secret_name = 2;
  string cause = 3;
}

//
// DeleteSecret
//
message DeleteSecretRequest {
  opendut.model.secret.SecretId secret_id = 1;
}

message DeleteSecretResponse {
  oneof reply {
    DeleteSecretSuccess success = 1;
    DeleteSecretFailure failure = 2;
  }
}

message DeleteSecretSuccess {
  opendut.model.secret.SecretDescriptor secret_descriptor = 1;
}

message DeleteSecretFailure {
  oneof error {
    DeleteSecretFailureNotFound not_found = 1;
    DeleteSecretFailureConflict conflict = 2;
    DeleteSecretFailureInternal internal = 3;
  }
}

message DeleteSecretFailureNotFound {
  opendut.model.secret.SecretId secret_id = 1;
}

message DeleteSecretFailureConflict {
  opendut.model.secret.SecretId secret_id = 1;
  string cause = 2;
}

message DeleteSecretFailureInternal {
  opendut.model.secret.SecretId secret_id = 1;
  string cause = 2;
}

//
// ListSecrets
//
message ListSecretsRequest {}

message ListSecretsResponse {
  oneof reply {
    ListSecretsSuccess success = 1;
    ListSecretsFailure failure = 2;
  }
}

message ListSecretsSuccess {
  repeated opendut.model.secret.SecretDescriptor secrets = 1;
}

message ListSecretsFailure {
  oneof error {
    ListSecretsFailureInternal internal = 1;
  }
}

message ListSecretsFailureInternal {
  string cause = 1;
}
