syntax = "proto3";

package opendut.carl.services.test_manager;

import "opendut/model/cluster/cluster.proto";
import "opendut/model/viper/run.proto";
import "opendut/model/viper/test.proto";
import "opendut/model/viper/source.proto";
import "opendut/model/viper/suite.proto";

service TestManager {
  rpc StoreViperSourceDescriptor(StoreViperSourceDescriptorRequest) returns (StoreViperSourceDescriptorResponse) {}
  rpc DeleteViperSourceDescriptor(DeleteViperSourceDescriptorRequest) returns (DeleteViperSourceDescriptorResponse) {}
  rpc GetViperSourceDescriptor(GetViperSourceDescriptorRequest) returns (GetViperSourceDescriptorResponse) {}
  rpc ListViperSourceDescriptors(ListViperSourceDescriptorsRequest) returns (ListViperSourceDescriptorsResponse) {}

  rpc ListViperTestSuiteDescriptors(ListViperTestSuiteDescriptorsRequest) returns (ListViperTestSuiteDescriptorsResponse) {}

  rpc StoreViperTestDescriptor(StoreViperTestDescriptorRequest) returns (StoreViperTestDescriptorResponse) {}
  rpc DeleteViperTestDescriptor(DeleteViperTestDescriptorRequest) returns (DeleteViperTestDescriptorResponse) {}
  rpc GetViperTestDescriptor(GetViperTestDescriptorRequest) returns (GetViperTestDescriptorResponse) {}
  rpc ListViperTestDescriptors(ListViperTestDescriptorsRequest) returns (ListViperTestDescriptorsResponse) {}

  rpc StoreViperRunDeployment(StoreViperRunDeploymentRequest) returns (StoreViperRunDeploymentResponse) {}
  rpc DeleteViperRunDeployment(DeleteViperRunDeploymentRequest) returns (DeleteViperRunDeploymentResponse) {}
  rpc GetViperRunDeployment(GetViperRunDeploymentRequest) returns (GetViperRunDeploymentResponse) {}
  rpc ListViperRunDeployments(ListViperRunDeploymentsRequest) returns (ListViperRunDeploymentsResponse) {}
}


///////////////////////////
// ViperSourceDescriptor //
///////////////////////////

//
// StoreViperSourceDescriptor
//
message StoreViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceDescriptor source = 1;
}

message StoreViperSourceDescriptorResponse {
  oneof reply {
    StoreViperSourceDescriptorSuccess success = 1;
    StoreViperSourceDescriptorFailure failure = 2;
  }
}

message StoreViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message StoreViperSourceDescriptorFailure {
  oneof error {
    StoreViperSourceDescriptorFailureInternal internal = 1;
  }
}

message StoreViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.model.viper.ViperSourceName source_name = 2;
  string cause = 3;
}


//
// DeleteViperSourceDescriptor
//
message DeleteViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorResponse {
  oneof reply {
    DeleteViperSourceDescriptorSuccess success = 1;
    DeleteViperSourceDescriptorFailure failure = 2;
  }
}

message DeleteViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorFailure {
  oneof error {
    DeleteViperSourceDescriptorFailureSourceNotFound source_not_found = 1;
    DeleteViperSourceDescriptorFailureInternal internal = 4;
    DeleteViperSourceDescriptorFailureTestExists test_exists = 5;
  }
}

message DeleteViperSourceDescriptorFailureSourceNotFound {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  optional opendut.model.viper.ViperSourceName source_name = 2;
  string cause = 3;
}

message DeleteViperSourceDescriptorFailureTestExists {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.model.viper.ViperTestId test_id = 2;
}


//
// GetViperSourceDescriptor
//
message GetViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperSourceDescriptorResponse {
  oneof reply {
    GetViperSourceDescriptorSuccess success = 1;
    GetViperSourceDescriptorFailure failure = 2;
  }
}

message GetViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceDescriptor descriptor = 1;
}

message GetViperSourceDescriptorFailure {
  oneof error {
    GetViperSourceDescriptorFailureSourceNotFound source_not_found = 1;
    GetViperSourceDescriptorFailureInternal internal = 2;
  }
}

message GetViperSourceDescriptorFailureSourceNotFound {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  string cause = 2;
}


//
// ListViperSourceDescriptors
//
message ListViperSourceDescriptorsRequest {}

message ListViperSourceDescriptorsResponse {
  oneof reply {
    ListViperSourceDescriptorsSuccess success = 1;
    ListViperSourceDescriptorsFailure failure = 2;
  }
}

message ListViperSourceDescriptorsSuccess {
  repeated opendut.model.viper.ViperSourceDescriptor sources = 1;
}

message ListViperSourceDescriptorsFailure {
  oneof error {
      ListViperSourceDescriptorsFailureInternal internal = 1;
  }
}

message ListViperSourceDescriptorsFailureInternal {
  string cause = 1;
}



//////////////////////////////
// ViperTestSuiteDescriptor //
//////////////////////////////

//
// ListViperTestSuiteDescriptors
//
message ListViperTestSuiteDescriptorsRequest {}

message ListViperTestSuiteDescriptorsResponse {
  oneof reply {
    ListViperTestSuiteDescriptorsSuccess success = 1;
    ListViperTestSuiteDescriptorsFailure failure = 2;
  }
}

message ListViperTestSuiteDescriptorsSuccess {
  repeated opendut.model.viper.ViperTestSuiteDescriptor suites = 1;
}

message ListViperTestSuiteDescriptorsFailure {
  oneof error {
      ListViperTestSuiteDescriptorsFailureInternal internal = 1;
  }
}

message ListViperTestSuiteDescriptorsFailureInternal {
  string cause = 1;
}



/////////////////////////
// ViperTestDescriptor //
/////////////////////////

//
// StoreViperTestDescriptor
//
message StoreViperTestDescriptorRequest {
  opendut.model.viper.ViperTestDescriptor test = 1;
}

message StoreViperTestDescriptorResponse {
  oneof reply {
    StoreViperTestDescriptorSuccess success = 1;
    StoreViperTestDescriptorFailure failure = 2;
  }
}

message StoreViperTestDescriptorSuccess {
  opendut.model.viper.ViperTestId test_id = 1;
}

message StoreViperTestDescriptorFailure {
  oneof error {
    StoreViperTestDescriptorFailureInternal internal = 1;
  }
}

message StoreViperTestDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}


//
// DeleteViperTestDescriptor
//
message DeleteViperTestDescriptorRequest {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestDescriptorResponse {
  oneof reply {
    DeleteViperTestDescriptorSuccess success = 1;
    DeleteViperTestDescriptorFailure failure = 2;
  }
}

message DeleteViperTestDescriptorSuccess {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestDescriptorFailure {
  oneof error {
    DeleteViperTestDescriptorFailureTestNotFound test_not_found = 1;
    DeleteViperTestDescriptorFailureInternal internal = 4;
    DeleteViperTestDescriptorFailureDeploymentExists deployment_exists = 5;
  }
}

message DeleteViperTestDescriptorFailureTestNotFound {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}

message DeleteViperTestDescriptorFailureDeploymentExists {
  opendut.model.viper.ViperTestId test_id = 1;
  opendut.model.cluster.ClusterId cluster_id = 2;
}


//
// GetViperTestDescriptor
//
message GetViperTestDescriptorRequest {
  opendut.model.viper.ViperTestId test_id = 1;
}

message GetViperTestDescriptorResponse {
  oneof reply {
    GetViperTestDescriptorSuccess success = 1;
    GetViperTestDescriptorFailure failure = 2;
  }
}

message GetViperTestDescriptorSuccess {
  opendut.model.viper.ViperTestDescriptor descriptor = 1;
}

message GetViperTestDescriptorFailure {
  oneof error {
    GetViperTestDescriptorFailureTestNotFound test_not_found = 1;
    GetViperTestDescriptorFailureInternal internal = 2;
  }
}

message GetViperTestDescriptorFailureTestNotFound {
  opendut.model.viper.ViperTestId test_id = 1;
}

message GetViperTestDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}


//
// ListViperTestDescriptors
//
message ListViperTestDescriptorsRequest {}

message ListViperTestDescriptorsResponse {
  oneof reply {
    ListViperTestDescriptorsSuccess success = 1;
    ListViperTestDescriptorsFailure failure = 2;
  }
}

message ListViperTestDescriptorsSuccess {
  repeated opendut.model.viper.ViperTestDescriptor tests = 1;
}

message ListViperTestDescriptorsFailure {
  oneof error {
      ListViperTestDescriptorsFailureInternal internal = 1;
  }
}

message ListViperTestDescriptorsFailureInternal {
  string cause = 1;
}


////////////////////////
// ViperRunDeployment //
////////////////////////

//
// StoreViperRunDeployment
//
message StoreViperRunDeploymentRequest {
  opendut.model.viper.ViperRunDeployment run = 1;
}

message StoreViperRunDeploymentResponse {
  oneof reply {
    StoreViperRunDeploymentSuccess success = 1;
    StoreViperRunDeploymentFailure failure = 2;
  }
}

message StoreViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunId run_id = 1;
}

message StoreViperRunDeploymentFailure {
  oneof error {
    StoreViperRunDeploymentFailureInternal internal = 1;
  }
}

message StoreViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// DeleteViperRunDeployment
//
message DeleteViperRunDeploymentRequest {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentResponse {
  oneof reply {
    DeleteViperRunDeploymentSuccess success = 1;
    DeleteViperRunDeploymentFailure failure = 2;
  }
}

message DeleteViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentFailure {
  oneof error {
    DeleteViperRunDeploymentFailureRunNotFound run_not_found = 1;
    DeleteViperRunDeploymentFailureInternal internal = 4;
  }
}

message DeleteViperRunDeploymentFailureRunNotFound {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// GetViperRunDeployment
//
message GetViperRunDeploymentRequest {
  opendut.model.viper.ViperRunId run_id = 1;
}

message GetViperRunDeploymentResponse {
  oneof reply {
    GetViperRunDeploymentSuccess success = 1;
    GetViperRunDeploymentFailure failure = 2;
  }
}

message GetViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunDeployment deployment = 1;
}

message GetViperRunDeploymentFailure {
  oneof error {
    GetViperRunDeploymentFailureRunNotFound run_not_found = 1;
    GetViperRunDeploymentFailureInternal internal = 2;
  }
}

message GetViperRunDeploymentFailureRunNotFound {
  opendut.model.viper.ViperRunId run_id = 1;
}

message GetViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// ListViperRunDeployments
//
message ListViperRunDeploymentsRequest {}

message ListViperRunDeploymentsResponse {
  oneof reply {
    ListViperRunDeploymentsSuccess success = 1;
    ListViperRunDeploymentsFailure failure = 2;
  }
}

message ListViperRunDeploymentsSuccess {
  repeated opendut.model.viper.ViperRunDeployment runs = 1;
}

message ListViperRunDeploymentsFailure {
  oneof error {
      ListViperRunDeploymentsFailureInternal internal = 1;
  }
}

message ListViperRunDeploymentsFailureInternal {
  string cause = 1;
}
