syntax = "proto3";

package opendut.carl.services.viper_manager;

import "opendut/model/cluster/cluster.proto";
import "opendut/model/viper/run.proto";
import "opendut/model/viper/test.proto";
import "opendut/model/viper_test_id.proto";
import "opendut/model/viper/source.proto";
import "opendut/model/viper/suite.proto";
import "opendut/viper/rt/test_suite.proto";

service ViperManager {
  rpc StoreViperSourceDescriptor(StoreViperSourceDescriptorRequest) returns (StoreViperSourceDescriptorResponse) {}
  rpc DeleteViperSourceDescriptor(DeleteViperSourceDescriptorRequest) returns (DeleteViperSourceDescriptorResponse) {}
  rpc GetViperSourceDescriptor(GetViperSourceDescriptorRequest) returns (GetViperSourceDescriptorResponse) {}
  rpc ListViperSourceDescriptors(ListViperSourceDescriptorsRequest) returns (ListViperSourceDescriptorsResponse) {}

  rpc GetViperTestSuiteParameters(GetViperTestSuiteParametersRequest) returns (GetViperTestSuiteParametersResponse) {}

  rpc StoreViperTestRunDescriptor(StoreViperTestRunDescriptorRequest) returns (StoreViperTestRunDescriptorResponse) {}
  rpc DeleteViperTestRunDescriptor(DeleteViperTestRunDescriptorRequest) returns (DeleteViperTestRunDescriptorResponse) {}
  rpc GetViperTestRunDescriptor(GetViperTestRunDescriptorRequest) returns (GetViperTestRunDescriptorResponse) {}
  rpc ListViperTestRunDescriptors(ListViperTestRunDescriptorsRequest) returns (ListViperTestRunDescriptorsResponse) {}

  rpc StoreViperRunDeployment(StoreViperRunDeploymentRequest) returns (StoreViperRunDeploymentResponse) {}
  rpc DeleteViperRunDeployment(DeleteViperRunDeploymentRequest) returns (DeleteViperRunDeploymentResponse) {}
  rpc GetViperRunDeployment(GetViperRunDeploymentRequest) returns (GetViperRunDeploymentResponse) {}
  rpc ListViperRunDeployments(ListViperRunDeploymentsRequest) returns (ListViperRunDeploymentsResponse) {}
}


///////////////////////////
// ViperSourceDescriptor //
///////////////////////////

//
// StoreViperSourceDescriptor
//
message StoreViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceDescriptor source = 1;
}

message StoreViperSourceDescriptorResponse {
  oneof reply {
    StoreViperSourceDescriptorSuccess success = 1;
    StoreViperSourceDescriptorFailure failure = 2;
  }
}

message StoreViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message StoreViperSourceDescriptorFailure {
  oneof error {
    StoreViperSourceDescriptorFailureInternal internal = 1;
  }
}

message StoreViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.viper.rt.test_suite.ViperTestSuiteIdentifier source_name = 2;
  string cause = 3;
}


//
// DeleteViperSourceDescriptor
//
message DeleteViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorResponse {
  oneof reply {
    DeleteViperSourceDescriptorSuccess success = 1;
    DeleteViperSourceDescriptorFailure failure = 2;
  }
}

message DeleteViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorFailure {
  oneof error {
    DeleteViperSourceDescriptorFailureSourceNotFound source_not_found = 1;
    DeleteViperSourceDescriptorFailureInternal internal = 4;
    DeleteViperSourceDescriptorFailureTestExists test_exists = 5;
  }
}

message DeleteViperSourceDescriptorFailureSourceNotFound {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message DeleteViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  optional opendut.viper.rt.test_suite.ViperTestSuiteIdentifier source_name = 2;
  string cause = 3;
}

message DeleteViperSourceDescriptorFailureTestExists {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.model.viper.ViperTestId test_id = 2;
}


//
// GetViperSourceDescriptor
//
message GetViperSourceDescriptorRequest {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperSourceDescriptorResponse {
  oneof reply {
    GetViperSourceDescriptorSuccess success = 1;
    GetViperSourceDescriptorFailure failure = 2;
  }
}

message GetViperSourceDescriptorSuccess {
  opendut.model.viper.ViperSourceDescriptor descriptor = 1;
}

message GetViperSourceDescriptorFailure {
  oneof error {
    GetViperSourceDescriptorFailureSourceNotFound source_not_found = 1;
    GetViperSourceDescriptorFailureInternal internal = 2;
  }
}

message GetViperSourceDescriptorFailureSourceNotFound {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperSourceDescriptorFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  string cause = 2;
}


//
// ListViperSourceDescriptors
//
message ListViperSourceDescriptorsRequest {}

message ListViperSourceDescriptorsResponse {
  oneof reply {
    ListViperSourceDescriptorsSuccess success = 1;
    ListViperSourceDescriptorsFailure failure = 2;
  }
}

message ListViperSourceDescriptorsSuccess {
  repeated opendut.model.viper.ViperSourceDescriptor sources = 1;
}

message ListViperSourceDescriptorsFailure {
  oneof error {
      ListViperSourceDescriptorsFailureInternal internal = 1;
  }
}

message ListViperSourceDescriptorsFailureInternal {
  string cause = 1;
}



//////////////////////////////
// ViperTestSuiteParameters //
//////////////////////////////

//
// GetViperTestSuiteParameters
//
message GetViperTestSuiteParametersRequest {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperTestSuiteParametersResponse {
  oneof reply {
    GetViperTestSuiteParametersSuccess success = 1;
    GetViperTestSuiteParametersFailure failure = 2;
  }
}

message GetViperTestSuiteParametersSuccess {
  opendut.model.viper.ViperTestSuiteParameters descriptor = 1;
}

message GetViperTestSuiteParametersFailure {
  oneof error {
    GetViperTestSuiteParametersFailureSourceNotFound source_not_found = 1;
    GetViperTestSuiteParametersFailureInternal internal = 2;
    GetViperTestSuiteParametersFailureCompilation compilation = 3;
    GetViperTestSuiteParametersFailureViperRuntime viper_runtime = 5;
  }
}

message GetViperTestSuiteParametersFailureSourceNotFound {
  opendut.model.viper.ViperSourceId source_id = 1;
}

message GetViperTestSuiteParametersFailureCompilation {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.viper.rt.test_suite.ViperTestSuiteIdentifier source_name = 2;
}

message GetViperTestSuiteParametersFailureViperRuntime {
  opendut.model.viper.ViperSourceId source_id = 1;
  opendut.viper.rt.test_suite.ViperTestSuiteIdentifier source_name = 2;
}

message GetViperTestSuiteParametersFailureInternal {
  opendut.model.viper.ViperSourceId source_id = 1;
  string cause = 2;
}



/////////////////////////
// ViperTestRunDescriptor //
/////////////////////////

//
// StoreViperTestRunDescriptor
//
message StoreViperTestRunDescriptorRequest {
  opendut.model.viper.ViperTestRunDescriptor test = 1;
}

message StoreViperTestRunDescriptorResponse {
  oneof reply {
    StoreViperTestRunDescriptorSuccess success = 1;
    StoreViperTestRunDescriptorFailure failure = 2;
  }
}

message StoreViperTestRunDescriptorSuccess {
  opendut.model.viper.ViperTestId test_id = 1;
}

message StoreViperTestRunDescriptorFailure {
  oneof error {
    StoreViperTestRunDescriptorFailureInternal internal = 1;
  }
}

message StoreViperTestRunDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}


//
// DeleteViperTestRunDescriptor
//
message DeleteViperTestRunDescriptorRequest {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestRunDescriptorResponse {
  oneof reply {
    DeleteViperTestRunDescriptorSuccess success = 1;
    DeleteViperTestRunDescriptorFailure failure = 2;
  }
}

message DeleteViperTestRunDescriptorSuccess {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestRunDescriptorFailure {
  oneof error {
    DeleteViperTestRunDescriptorFailureTestNotFound test_not_found = 1;
    DeleteViperTestRunDescriptorFailureInternal internal = 4;
    DeleteViperTestDescriptorFailureViperRunDeploymentExists viper_run_deployment_exists = 5;
  }
}

message DeleteViperTestRunDescriptorFailureTestNotFound {
  opendut.model.viper.ViperTestId test_id = 1;
}

message DeleteViperTestRunDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}

message DeleteViperTestRunDescriptorFailureDeploymentExists {
  opendut.model.viper.ViperTestId test_id = 1;
  opendut.model.cluster.ClusterId cluster_id = 2;
}

message DeleteViperTestDescriptorFailureViperRunDeploymentExists {
  opendut.model.viper.ViperTestId test_id = 1;
  opendut.model.viper.ViperRunId run_id = 2;
}


//
// GetViperTestRunDescriptor
//
message GetViperTestRunDescriptorRequest {
  opendut.model.viper.ViperTestId test_id = 1;
}

message GetViperTestRunDescriptorResponse {
  oneof reply {
    GetViperTestRunDescriptorSuccess success = 1;
    GetViperTestRunDescriptorFailure failure = 2;
  }
}

message GetViperTestRunDescriptorSuccess {
  opendut.model.viper.ViperTestRunDescriptor descriptor = 1;
}

message GetViperTestRunDescriptorFailure {
  oneof error {
    GetViperTestRunDescriptorFailureTestNotFound test_not_found = 1;
    GetViperTestRunDescriptorFailureInternal internal = 2;
  }
}

message GetViperTestRunDescriptorFailureTestNotFound {
  opendut.model.viper.ViperTestId test_id = 1;
}

message GetViperTestRunDescriptorFailureInternal {
  opendut.model.viper.ViperTestId test_id = 1;
  string cause = 2;
}


//
// ListViperTestRunDescriptors
//
message ListViperTestRunDescriptorsRequest {}

message ListViperTestRunDescriptorsResponse {
  oneof reply {
    ListViperTestRunDescriptorsSuccess success = 1;
    ListViperTestRunDescriptorsFailure failure = 2;
  }
}

message ListViperTestRunDescriptorsSuccess {
  repeated opendut.model.viper.ViperTestRunDescriptor tests = 1;
}

message ListViperTestRunDescriptorsFailure {
  oneof error {
      ListViperTestRunDescriptorsFailureInternal internal = 1;
  }
}

message ListViperTestRunDescriptorsFailureInternal {
  string cause = 1;
}


////////////////////////
// ViperRunDeployment //
////////////////////////

//
// StoreViperRunDeployment
//
message StoreViperRunDeploymentRequest {
  opendut.model.viper.ViperRunDeployment run = 1;
}

message StoreViperRunDeploymentResponse {
  oneof reply {
    StoreViperRunDeploymentSuccess success = 1;
    StoreViperRunDeploymentFailure failure = 2;
  }
}

message StoreViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunId run_id = 1;
}

message StoreViperRunDeploymentFailure {
  oneof error {
    StoreViperRunDeploymentFailureInternal internal = 1;
  }
}

message StoreViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// DeleteViperRunDeployment
//
message DeleteViperRunDeploymentRequest {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentResponse {
  oneof reply {
    DeleteViperRunDeploymentSuccess success = 1;
    DeleteViperRunDeploymentFailure failure = 2;
  }
}

message DeleteViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentFailure {
  oneof error {
    DeleteViperRunDeploymentFailureRunNotFound run_not_found = 1;
    DeleteViperRunDeploymentFailureInternal internal = 4;
  }
}

message DeleteViperRunDeploymentFailureRunNotFound {
  opendut.model.viper.ViperRunId run_id = 1;
}

message DeleteViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// GetViperRunDeployment
//
message GetViperRunDeploymentRequest {
  opendut.model.viper.ViperRunId run_id = 1;
}

message GetViperRunDeploymentResponse {
  oneof reply {
    GetViperRunDeploymentSuccess success = 1;
    GetViperRunDeploymentFailure failure = 2;
  }
}

message GetViperRunDeploymentSuccess {
  opendut.model.viper.ViperRunDeployment deployment = 1;
}

message GetViperRunDeploymentFailure {
  oneof error {
    GetViperRunDeploymentFailureRunNotFound run_not_found = 1;
    GetViperRunDeploymentFailureInternal internal = 2;
  }
}

message GetViperRunDeploymentFailureRunNotFound {
  opendut.model.viper.ViperRunId run_id = 1;
}

message GetViperRunDeploymentFailureInternal {
  opendut.model.viper.ViperRunId run_id = 1;
  string cause = 2;
}


//
// ListViperRunDeployments
//
message ListViperRunDeploymentsRequest {}

message ListViperRunDeploymentsResponse {
  oneof reply {
    ListViperRunDeploymentsSuccess success = 1;
    ListViperRunDeploymentsFailure failure = 2;
  }
}

message ListViperRunDeploymentsSuccess {
  repeated opendut.model.viper.ViperRunDeployment runs = 1;
}

message ListViperRunDeploymentsFailure {
  oneof error {
      ListViperRunDeploymentsFailureInternal internal = 1;
  }
}

message ListViperRunDeploymentsFailureInternal {
  string cause = 1;
}
