name: Install Kernel Modules
description: Install Kernel Modules

runs:
  using: "composite"
  steps:
    - name: Install and load 'vcan' and 'can-gw' kernel modules
      shell: bash
      run: |
        kernel_version="$(uname -r | cut -d- -f1)"
        sudo apt-get update
        # With the new 6.15 development kernel, the Canonical Kernel Team has also rolled out the deprecation of the linux-modules-extra package, shipping all the kernel modules via the linux-modules package.
        # See https://discourse.ubuntu.com/t/kernel-development-release-cadence-and-deprecation-of-linux-modules-extra/65176
        if dpkg --compare-versions "$kernel_version" lt "6.15"; then
          sudo apt-get install -y \
            linux-modules-extra-$(uname -r)
        fi
        sudo modprobe vcan
        sudo modprobe can-gw max_hops=2
