{
 "title": "OpenDuT",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": {}
   },
   {
    "name": "peer_id",
    "label": "Peer ID",
    "query": {}
   },
   {
    "name": "root_name",
    "label": "Root name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "a4dbbe6a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "opendut-carl" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=~\"$service_name\" && rootName=~\"$root_name\" && resource.service.instance.id=~\"$peer_id\"} ",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Tempo",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "a4dbbe6a", "operator": "=", "scope": "resource", "tag": "service.instance.id" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=~\"$service_name\" && rootName=~\"$root_name\" && resource.service.instance.id=~\"$peer_id\"} | select(resource.service.instance.id, span.self_id)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Deployed Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    { "expr": "deployed_clusters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Configured Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    { "expr": "configured_clusters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    { "expr": "connected_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Registered Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    { "expr": "registered_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Edgar host RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "host_ram_used{exported_instance!=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edgar process RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_ram_used{exported_instance!=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edgar process CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_used{exported_instance!=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carl host RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "host_ram_used{exported_instance=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carl process RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_ram_used{exported_instance=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carl process CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_used{exported_instance=\"carl_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}