{
 "title": "OpenDuT Logs",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter", "label": "Full text" },
   {
    "name": "severity",
    "label": "Level",
    "query": {}
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Loki Logs - Last 1000",
   "type": "logs",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"$service_name\", level=~\"$severity\"} |= `$filter` | logfmt",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Loki Logs - ERRORS",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"$service_name\", level=~\"ERROR\"} |= `$filter` | logfmt"
    }
   ]
  },
  {
   "title": "Loki Log Levels",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=~\"$service_name\", level=~\"$severity\"} |= `$filter` | logfmt [$__auto]))"
    }
   ]
  }
 ]
}