{
 "title": "OpenDuT Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": {}
   },
   {
    "name": "peer_id",
    "label": "Service Instance ID",
    "query": {}
   },
   {
    "name": "root_name",
    "label": "Root name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "openDuT Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployed Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "deployed_clusters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Configured Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "configured_clusters", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "connected_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Registered Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "registered_peers", "legendFormat": "__auto" }
   ]
  },
  { "title": "EDGAR System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Edgar host RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "host_ram_used{exported_job!=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edgar process RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_ram_used{exported_job!=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edgar process CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_used{exported_job!=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CARL System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Carl host RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "host_ram_used{exported_job=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carl process RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_ram_used{exported_job=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carl process CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_used{exported_job=\"opendut-carl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Netbird System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Netbird process RAM used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netbird process CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(process_cpu_seconds_total - min_over_time(process_cpu_seconds_total[2m])) / 60 * 100",
     "legendFormat": "{{process_cpu_percentage}}"
    }
   ]
  },
  {
   "title": "Netbird grpc connected streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "management_grpc_connected_streams_ratio",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}