version: "3.9"

services:
  dummy:
    image: busybox  # required service to create network
    networks:
      - opendutnet

networks:
  opendutnet:
    name: opendut_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.32.0/24
          ip_range: 192.168.32.0/24
