ARG KEYCLOAK_VERSION=22.0.2

FROM maven:3.9-eclipse-temurin-21 as extension
WORKDIR /src
RUN git clone https://github.com/thomasdarimont/keycloak-extension-playground
WORKDIR /src/keycloak-extension-playground/github-enterprise-identity-provider
RUN mvn clean package


FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
RUN mkdir -p /mnt/rootfs
# Removes this warning "This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register."
RUN dnf remove -y subscription-manager
RUN dnf install --installroot /mnt/rootfs curl jq --releasever 9 --setopt install_weak_deps=false --nodocs -y; dnf --installroot /mnt/rootfs clean all
COPY ./resources/development/tls/insecure-development-ca.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

# Documentation:
# https://www.keycloak.org/server/containers
# https://github.com/keycloak/keycloak/issues/17438

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
USER root

COPY --from=ubi-micro-build /mnt/rootfs/usr/bin/curl /usr/bin/curl
COPY --from=ubi-micro-build /mnt/rootfs/usr/bin/jq /usr/bin/jq
COPY --from=ubi-micro-build /mnt/rootfs/usr/lib64/ /usr/lib64/
COPY --from=ubi-micro-build /etc/pki/ca-trust/extracted/ /etc/pki/ca-trust/extracted/

COPY --from=extension /src/keycloak-extension-playground/github-enterprise-identity-provider/target/github-enterprise-identity-provider-1.0.0.0-SNAPSHOT.jar /opt/keycloak/providers
RUN /opt/keycloak/bin/kc.sh build

USER keycloak
