auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

chunk_store_config:
  max_look_back_period: 120h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  retention_enabled: true
  compaction_interval: 10m
  retention_delete_delay: 1m
  retention_delete_worker_count: 150

limits_config:
  retention_period: 24h

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
