name: Rust common setup steps
description: Setup rust with cached dependencies

# https://docs.github.com/en/actions/learn-github-actions/expressions#contains
#
runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
      id: toolchain
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
    - name: Prepare Rust Toolchain Cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
          ~/work/opendut/opendut/.cargo-venv/
        key: rust-toolchain-${{ github.job }}-${{steps.toolchain.outputs.cachekey}}

    - name: Prepare Rust Dependency Cache
      uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
