
- name: Show environment variable configuration file for opendut setup
  debug:
    msg: "Environment file {{ opendut_env_secret_file }}"

- name: Set environment variable for CARL docker image version
  become: True
  ansible.builtin.lineinfile:
    path: "{{ opendut_env_secret_file }}"
    regexp: '^OPENDUT_CARL_IMAGE_VERSION='
    line: "OPENDUT_CARL_IMAGE_VERSION={{ opendut_carl_image_version }}"
  when: opendut_carl_image_version is defined

- name: Delete environment variable for CARL docker image version
  become: True
  ansible.builtin.lineinfile:
    path: "{{ opendut_env_secret_file }}"
    regexp: '^OPENDUT_CARL_IMAGE_VERSION='
    state: absent
  when: opendut_carl_image_version is not defined

- import_tasks: tasks/synchronize_facts_and_secrets.yaml
