- name: Check if provisioning is needed
  stat: path={{ repo_dir }}/.ci/deploy/localenv/data/secrets/.env
  register: provision_secrets_stat

- name: Provision
  when: not provision_secrets_stat.stat.exists
  block:
    - name: Provision secrets and initially create volumes
      command:
        cmd: "docker compose --file .ci/deploy/localenv/docker-compose.yml --file .ci/deploy/localenv/docker-compose.override.yml --env-file {{ opendut_compose_environment_path }} up --build provision-secrets"
        chdir: "{{ repo_dir }}"

    - name: Remove secrets directory
      file:
        path: "{{ repo_dir }}/.ci/deploy/localenv/data/secrets/"
        state: absent
      changed_when: false

    - import_tasks: tasks/synchronize_facts_and_secrets.yaml
