- name: Copy provisioned secrets to local env data directory
  command:
    # https://docs.docker.com/reference/cli/docker/container/cp/
    # the content of the source directory is copied into this directory
    cmd: "docker cp opendut-provision-secrets:/provision/. {{ repo_dir }}/.ci/deploy/localenv/data/secrets/"
    chdir: "{{ repo_dir }}"
  changed_when: false
