# Documentation:
#  https://www.keycloak.org/server/containers

ARG KEYCLOAK_VERSION

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION AS builder

# Keycloak configuration options: https://www.keycloak.org/server/all-config
# Configure postgres database vendor
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES="token-exchange,scripts,preview"

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build


FROM registry.access.redhat.com/ubi9 AS ubi-micro-build

RUN mkdir -p /mnt/rootfs \
    && dnf remove -y subscription-manager \
    && dnf install --installroot /mnt/rootfs curl jq \
           --releasever 9 \
           --setopt install_weak_deps=false \
           --nodocs -y \
    && dnf --installroot /mnt/rootfs clean all \
    && rpm --root /mnt/rootfs -e --nodeps setup


FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

LABEL image.version=$KEYCLOAK_VERSION

COPY --from=builder /opt/keycloak/ /opt/keycloak/

USER root
COPY --from=ubi-micro-build /mnt/rootfs /

# If any themes
# COPY themes/<nice-themes> /opt/keycloak/themes/<nice-themes>

USER keycloak

RUN /opt/keycloak/bin/kc.sh show-config

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

# https://www.keycloak.org/server/logging#_console_log_handler
# The default keycloak date format is '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n'
# which is incompatible with date format RFC3339.
CMD ["start", "--optimized", "--log-console-format='%d{yyyy-MM-dd HH:mm:ss.SSSz} %-5p [%c] (%t) %s%e%n'"]
