{
 "title": "OpenDuT Logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service name",
    "query": {}
   },
   { "name": "query_filter" }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\"} | logfmt | severity_text = `ERROR`"
    }
   ]
  },
  {
   "title": "Log lines grouped by service",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (count_over_time({service_name=~\"$service_name\"}| logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\"} | logfmt"
    }
   ]
  },
  {
   "title": "Levels",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity_text) (count_over_time({service_name=~\"$service_name\"} |= `$query_filter` | logfmt [$__auto]))"
    }
   ]
  }
 ]
}