# Docker Compose override file for local environment deployment
# This file can be used to customize or extend the default docker-compose.yml configuration. 

services:

  traefik:
    environment:
      - OPENDUT_TRAEFIK_CLIENT_AUTH_TYPE=RequireAndVerifyClientCert  # enable mTLS
    networks: !override
    - opendut_local

  traefik-internal:
    container_name: opendut-traefik-no-mtls
    environment:
      - OPENDUT_TRAEFIK_CLIENT_AUTH_TYPE=NoClientCert  # disable mTLS
    extends:
      file: ./docker-compose.yml
      service: traefik

    # override the ports to avoid conflict with the first Traefik instance
    ports: !override
      - "127.0.0.1:8082:8080"  # 2nd Traefik dashboard, only on localhost, do not expose publicly

  carl:
    environment:
      # network.tls.server.auth
      - OPENDUT_CARL_NETWORK_TLS_SERVER_AUTH_ENABLED=true  # enable mTLS
      - OPENDUT_CARL_NETWORK_TLS_SERVER_AUTH_CA

    # TODO: implement another healthcheck that sidesteps mTLS requirement
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]

  netbird-management:
    labels:
      - traefik.http.routers.netbird-api.tls.options=no-mtls@file
      - traefik.http.routers.netbird-wsproxy-mgmt.tls.options=no-mtls@file
      - traefik.http.routers.netbird-management.tls.options=no-mtls@file

  netbird-signal:
    labels:
      - traefik.http.routers.netbird-wsproxy-signal.tls.options=no-mtls@file
      - traefik.http.routers.netbird-signal.tls.options=no-mtls@file

  netbird-relay:
    labels:
      - traefik.http.routers.netbird-relay.tls.options=no-mtls@file


  cleo:
    environment:
      - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_ENABLED=true  # enable mTLS
      - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_CERTIFICATE=/provision/pki/deploy-intermediate/client-intermediate-test.pem
      - OPENDUT_CLEO_NETWORK_TLS_CLIENT_AUTH_KEY=/provision/pki/deploy-intermediate/client-intermediate-test.key

