ARG NETBIRD_MANAGEMENT_VERSION

FROM netbirdio/management:${NETBIRD_MANAGEMENT_VERSION}
RUN apt update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata ca-certificates curl jq gettext-base  \
    && apt clean  \
    && rm -rf /var/lib/apt/lists/*

COPY ./.ci/docker/netbird/netbird-api-functions.sh /netbird-api-functions.sh
COPY ./.ci/docker/netbird/netbird-management-health.sh /netbird-management-health.sh

COPY ./.ci/deploy/localenv/data/netbird/management_init.sh /management_init.sh

ENTRYPOINT [ "/management_init.sh" ]
