syntax = "proto3";

package opendut.model.viper;

import "opendut/model/viper/source.proto";
import "opendut/viper/rt/test_suite.proto";


message ViperTestSuiteDescriptor {
  opendut.viper.rt.test_suite.ViperTestSuiteIdentifier id = 1;
  ViperSourceId source = 2;
  repeated ViperTestParameterDescriptor parameters = 3;
}


message ViperTestParameterDescriptor {
  string key = 1;
  ViperTestParameterValueKind value_kind = 2;
}

enum ViperTestParameterValueKind {
  BOOLEAN = 0;
  NUMBER = 1;
  TEXT = 2;
}
