name: sbom
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Rust setup
        uses: ./.github/actions/rust-setup
        with:
          cargo-sbom: true

      - name: Generate SBOMs
        run: cargo ci licenses sbom
        shell: bash
      - name: Upload sbom artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: opendut-sbom
          path: ./target/ci/sbom/
          if-no-files-found: error
          retention-days: 30
