name: publish-helm-chart
on:
  push:
    paths:
      - '.ci/kubernetes/**'
      #- '.github/workflows/publish-helm-chart.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  publish-docker:
    name: "Publish helm chart"
    runs-on: "ubuntu-latest"
    permissions:
      packages: write  # required to publish Docker images

    steps:
      - name: Checkout Sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #4.1.5

      # Publish Docker image to GitHub Packages
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

      # Configure access to repository packages
      # - Goto https://github.com/orgs/eclipse-opendut/packages/container/opendut-carl/settings
      # - Click on "Manage Actions access" -> Add Repository
      # - Select the repository 'opendut' and click on "Add repository"
      # - Change role to "Write"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Package helm chart"
        run: helm package .ci/kubernetes/charts/opendut-chart-carl/ --dependency-update

      - name: "Publish helm chart"
        # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution
        if: github.repository_owner == 'eclipse-opendut'
        run: |
          export CHART_VERSION=$(grep -E '^version:' .ci/kubernetes/charts/opendut-chart-carl/Chart.yaml | tail -n1 | awk '{ print $2 }')
          helm push opendut-chart-carl-${CHART_VERSION}.tgz oci://ghcr.io/eclipse-opendut
